change command order
f0rkz/pysteamcmd pull request #11
Opened 2022-06-05 01:55 UTC by BryceRussell

steamcmd specifies that force_login_dir be used before loging in

2022-06-29 21:54 UTC, f0rkz commented
Hello, can you update this line to reflect the version change:

https://github.com/f0rkz/pysteamcmd/blob/master/setup.cfg#L3

2022-06-29 21:54 UTC, f0rkz requested changes
https://github.com/f0rkz/pysteamcmd/blob/master/setup.cfg#L3 please update the version number here.

2022-06-30 00:09 UTC, BryceRussell commented
Sorry about that, I updated it to 0.3.1 and also updated the copyright year on the license

2022-12-04 16:37 UTC, f0rkz approved these changes

2022-12-04 16:37 UTC, merged